### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by aouniradouan** [renatolaranjo/php-python-face-recognition#1]
Hi sir, after done all installation instructions it show me a white page with just the  title how can i resolve this problem
Thank You!

**Comment by renatolaranjo** [comment]
Hi. I must debug to understand what's going on. Feel free to add my contact below. 
**gtalk:** renatolaranjo@gmail.com
**skype:** renato.vieira.laranjo

**Comment by renatolaranjo** [comment]
A possibility to this white page is APP_URL and MIX_APP_URL must be the same URL your are accessing in your browser.

**Comment by aouniradouan** [comment]
The MIX_APP_URL is same APP_URL but it still not working

**Comment by aouniradouan** [comment]
When i download the script In the .env file the MIX_APP_URL was not found so i create one also PYTHON_PATH

**Comment by aouniradouan** [comment]
After Compiling
```
 DONE  Compiled successfully in 45604ms                                                                       2:31:03 PM

       Asset      Size   Chunks             Chunk Names
/css/app.css   224 KiB  /js/app  [emitted]  /js/app
  /js/app.js  4.28 MiB  /js/app  [emitted]  /js/app
```

**Comment by renatolaranjo** [comment]
Which version of php? I didn't tested with version 8.

**Comment by aouniradouan** [comment]
7.3

**Comment by renatolaranjo** [comment]
Is there any errors in your browser's console?

**Comment by renatolaranjo** [comment]
In my case I'm getting this...
`GET http://localhost:8000/api/list 404 (Not Found)`

**Comment by aouniradouan** [comment]
Yes
```
Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by renatolaranjo** [comment]
It seems command `npm run dev` is not creating those files. That's why you are getting a white page.

**Comment by aouniradouan** [comment]
how can i resolve this problem ?

**Comment by renatolaranjo** [comment]
Let's try some steps again:
1 - Set APP_URL your are using in my case: `localhost:8000` cause I'm running artisan server. 
2 - MIX_APP_URL="${APP_URL}" in your .env
3 - npm run dev 

After that, you must see all requests in your browser console like this: **your_app_url**/api/list for example. In my case: http://localhost:8000/api/list

If, error 404 related to app,js and app.css still happening, check it out if you find those files in your  public folder.

**Comment by renatolaranjo** [comment]
@aouniradouan Redwan! It has been a while since we have discussed this issue. Now, I have created two approaches for installation and configuration: Vagrant and Docker. Any questions or suggestions, let me know.

Regards
